<?php if ($this->isTagalysEnabled()): ?>
    <?php
        $currency = $this->getCurrentCurrency();
        $apiCredentials = $this->apiCredentials();
    ?>
    <script>
        var config = {
            paths:{
                "tagalys":"https://s3-ap-southeast-1.amazonaws.com/tagalys-assets/tagalys-plugins-v4"
            },
            shim:{
                'tagalys':{
                    'deps':['jquery', 'jquery/ui']
                }
            }
        };
        require.config(config);

        require(['jquery', 'jquery/ui', 'tagalys'], function($){ 
            try {
                $.fn.tagalys_public_api.server = '<?php echo $apiCredentials['api_server'] ?>';
                $.fn.tagalys_public_api.identification = {"client_code":"<?php echo $apiCredentials['client_code'] ?>","api_key":"<?php echo $apiCredentials['public_api_key'] ?>","store_id":"<?php echo $this->getCurrentStoreId() ?>"};
                var tagalys_context_opts = {
                    api_server: '<?php echo $apiCredentials['api_server'] ?>',
                    api_identification: {"client_code":"<?php echo $apiCredentials['client_code'] ?>","api_key":"<?php echo $apiCredentials['public_api_key'] ?>","store_id":"<?php echo $this->getCurrentStoreId() ?>","currency":"<?php echo $currency['id']; ?>"},
                    currency: {
                        label: "<?php echo $currency['label']; ?>",
                        exchange_rate: "<?php echo  $currency['exchange_rate']; ?>",
                        fractional_digits:"<?php echo  $currency['fractional_digits']; ?>"
                    }
                };
                var user_id = $.fn.tagalys_analytics.getCookie('__ta_user_id');
                if(user_id != ""){
                  tagalys_context_opts.user_id = user_id;
                }
                $('body').tagalys_context(tagalys_context_opts);
            }
            catch(err) {
                
            }
        });
    </script>
<?php endif; ?>